---
name: Bug Report
about: Create a report to help us improve
title: '[BUG] '
labels: ['bug', 'triage']
assignees: ''
---

## 🐛 Bug Description

A clear and concise description of what the bug is.

## 🔄 Steps to Reproduce

Steps to reproduce the behavior:

1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

## ✅ Expected Behavior

A clear and concise description of what you expected to happen.

## ❌ Actual Behavior

A clear and concise description of what actually happened.

## 📸 Screenshots

If applicable, add screenshots to help explain your problem.

## 🌍 Environment

- **Go version**: [e.g. 1.21.0]
- **Gomiger version**: [e.g. v1.0.0]
- **Database**: [e.g. MongoDB 6.0, PostgreSQL 14]
- **Operating System**: [e.g. Ubuntu 22.04, macOS 14.0, Windows 11]
- **Architecture**: [e.g. amd64, arm64]

## 📋 Additional Context

Add any other context about the problem here.

## 🔍 Code Example

If applicable, provide a minimal code example that reproduces the issue:

```go
// Your code here
```

## 📝 Migration File

If the issue is related to a specific migration, please include the migration file:

```go
// Your migration code here
```

## 📊 Error Logs

If applicable, include relevant error logs:

```
Error logs here
```

## 🤔 Possible Solution

If you have ideas on how to fix the issue, please describe them here.