blank_issues_enabled: false
contact_links:
  - name: 💬 GitHub Discussions
    url: https://github.com/ParteeLabs/gomiger/discussions
    about: Ask questions, share ideas, and discuss Gomiger with the community
  - name: 🔒 Security Issues
    url: mailto:security@parteelabs.com
    about: Please report security vulnerabilities via email (not public issues)
  - name: 📚 Documentation
    url: https://github.com/ParteeLabs/gomiger/tree/main/docs
    about: Check our comprehensive documentation and guides
  - name: 🚀 Examples
    url: https://github.com/ParteeLabs/gomiger/tree/main/examples
    about: Browse working examples and sample projects
